# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Bar.create([
  { :name => "Booker & Dax", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "Butterfly", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "Clover Club", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "Dead Rabbit", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "Dutch Kills", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "Employees Only", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "Louis 649", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "Macao Trading Company", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "Maison Premiere", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "PDT", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "The Rum House", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "Pegu Club", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "Pouring Ribbons", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "The Raines Law Room", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "The Beagle", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "Ward III", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" }
], :without_protection => true )



Dish.create([
  { :name => "main", :restaurant_id => 1, :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "side", :restaurant_id => 1, :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "dessert", :restaurant_id => 2, :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" },
  { :name => "main", :restaurant_id => 2, :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00" }
], :without_protection => true )



Restaurant.create([
  { :name => "Stanton Social and Beauty & Essex", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "L&W Oyster House", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Maialino", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "ACME", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Momofuku Ma Peche", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "The General", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "COLONIE", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Atera", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Mercadito", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Cole's Greenwich Village", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Gramercy Terrace", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Casa Mono & Bar Jamon", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Landmarc", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "SD26 Restaurant & Wine Bar", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "All'Onda", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Momofuku Ssam Bar", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Dinosaur Bar-B-Que", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Red Rooster & Ginny's Supper Club", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Hill Country Barbecue Market", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "PORTER HOUSE NEW YORK", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "The Meatball Shop", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "The Pines", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "A Voce", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Maharlika Filipino Moderno", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Aureole", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Edi & The Wolf \nSeasonal Restaurant & Weinbar", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Pies 'n' Thighs", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "The Marrow", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Allswell", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Blue Hill and Blue Hill at Stone Barns", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Blue Smoke", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "brushstroke", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Cafe 2 and Terrace at MoMa\nTerrace 5 (USHG)", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Char No. 4", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Commerce", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Crown", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "dirt candy", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Ed's Chowder House", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Gramercy Tavern", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Il Buco Alimentari & Vineria", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "L'Apicio", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Micheal's", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Mile End \nMile End Sandwich", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "North End Grill", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Oceana", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Osteria Morini", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Rickshaw Dumpling Bar", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Telepan", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "The Modern", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "The Smith", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "The Yankees", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Tia Pol", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Union Square Cafe", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Untitled at the Whitney", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Willow Road", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "ALDEA", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil },
  { :name => "Legends Hospitality at Yankee Stadium", :created_at => "2001-01-01 00:00:00", :updated_at => "2001-01-01 00:00:00", :kind => nil }
], :without_protection => true )



User.create([
  { :first_name => nil, :last_name => nil, :email => nil, :password_hash => nil, :password_salt => nil, :created_at => "2013-04-22 23:34:01", :updated_at => "2013-04-22 23:34:01", :username => "me" },
  { :first_name => nil, :last_name => nil, :email => nil, :password_hash => nil, :password_salt => nil, :created_at => "2013-04-22 23:36:46", :updated_at => "2013-04-22 23:36:46", :username => "you" },
  { :first_name => nil, :last_name => nil, :email => nil, :password_hash => nil, :password_salt => nil, :created_at => "2013-04-22 23:54:18", :updated_at => "2013-04-22 23:54:18", :username => "hey" }
], :without_protection => true )




